### ISSUE TITLE
error in css 

### ISSUE THREAD

**Issue by JllRogen** [chenxch/vite-plugin-dynamic-base#24]
error in css 
```css
.loginBg {
  height: 100%;
  width: 100%;
  background-image: url('../assets/imgs/background.png');
  background-repeat: no-repeat;
  background-size: cover;
  background-position: left center;
  position: relative;
}
```

after build  
```css
.loginBg[data-v-83a391f8] {
  height: 100%;
  width: 100%;
  background-image: url("/__dynamic_base__/assets/background-ec1cda62.png");
  background-repeat: no-repeat;
  background-size: cover;
  background-position: left center;
  position: relative;
}
```
i need in css file use realative path
